apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      hostname: producer
      containers:
        - env:
          image: producer
          imagePullPolicy: IfNotPresent
          name: producer
